### ISSUE TITLE
Acrid not running for one second after meleeing (M1)

### ISSUE THREAD

**Issue by HellQDecor** [goldenguy00/AutoSprint#4]
I've made an unlisted medal clip for u to see what I mean exactly:
https://medal.tv/games/ror-2/clips/iAhmnCCrzz1lswPA0/d1337AGrdZEa?invite=cr-MSxBMWwsNjI0ODI3NDQs
in the clip, after i did a melee attack, i waited for my character to start running automatically again; which it takes one second to do even if it should be allowed to
i also showcased how the rest of abilities doesn't faulter the dog's running capabilities, only the melees

**Comment by HellQDecor** [comment]
i found an interesting quirk of this bug;
trying to fight the "not being able to run properly" allegations by trying to run manually after meleeing would actually just make me stop running; and when i release the sprint button i start sprinting properly again
holding down the sprint button after melee-ing: https://medal.tv/games/ror-2/clips/iAhusl1AeJxzh3Jnn/d1337uKh4CDG?invite=cr-MSx0RXksNjI0ODI3NDQs
tapping the sprint button after melee-ing: https://medal.tv/games/ror-2/clips/iAhwWKOCY3UZ1Z5gm/d13377eoKCbQ?invite=cr-MSwzdmgsNjI0ODI3NDQs

**Comment by HellQDecor** [comment]
coincidentally, the tap running makes this bug not a huge issue but it would be a nice qol fix

**Comment by goldenguy00** [comment]
its due to the animation lasting a long time, which is usually a good indicator on when a skill should be cancelled. adding another special case for this... im highly considering a full rewrite of how the mod works since im having to hard code about a dozen special cases at this point, which was what i was trying to avoid in the first place. will be fixed in next update.

**Comment by goldenguy00** [comment]
adding in 1.0.9

**Comment by HellQDecor** [comment]
alr sick
